version: '3'

networks:

    backend:

services:

    nginx:
        image: nginx:1.21.6-alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "3131:443"
        environment:
            - NGINX_HOST=nginx
        restart: always
        depends_on:
            - php
        networks:
            - backend

    php:
        build: containers/php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
            - "./web:/var/www/html"
            - "./volumes:/var/www/volumes"
        #environment:
            #- PHP_OPCACHE_ENABLED=yes
        env_file:
            - ".env"
        depends_on:
            - composer
            - mysql
        networks:
            - backend

    composer:
        image: composer
        volumes:
            - "./web/app:/app"
        command: install

    pma:
        image: phpmyadmin/phpmyadmin:5.1.3
        ports:
            - "42069:80"
        environment:
            - PMA_HOST=mysql
            - UPLOAD_LIMIT=300M
        restart: always
        depends_on:
            - mysql
        networks:
            - backend

    mysql:
        image: mysql:8.0.21
        restart: always
        command:
            - "mysqld"
            - "--information-schema-stats-expiry=0"
        env_file:
            - ".env"
        volumes:
            - "./data/db:/var/lib/mysql"
            - "./etc/sql:/etc/mysql/conf.d"
        networks:
            - backend
